version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: main
      PGADMIN_DEFAULT_EMAIL: matheuspelo123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      DB_URL: postgresql+psycopg2://postgresql/main?user=admin&password=adminpass
  
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: main
      PGADMIN_DEFAULT_EMAIL: matheuspelo123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      DB_URL: postgresql+psycopg2://postgresql/main?user=admin&password=adminpass
    volumes: 
      - /var/cache/postgres_data:/var/lib/postgresql/data


  postgresql-test:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: main
      PGADMIN_DEFAULT_EMAIL: matheuspelo123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      DB_URL: postgresql+psycopg2://postgresql/main?user=admin&password=adminpass
    volumes: 
      - /var/cache/postgres_data_test:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: main
      PGADMIN_DEFAULT_EMAIL: matheuspelo123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      DB_URL: postgresql+psycopg2://postgresql/main?user=admin&password=adminpass
    ports:
      - 5050:80
    depends_on:
      - postgresql
